### ISSUE TITLE
Some questions about anti-xray in world_nether

### ISSUE THREAD

**Issue by LuckyODO** [stonar96/RayTraceAntiXray#38]
I noticed in the “Recommended Settings” that the note says  
```
      # Note that ancient_debris never generates naturally exposed to air.
      # Normal engine-mode: 1 is sufficient, disable ray tracing in the nether.
```
In fact, players can see “ancient_debris” in the lava when they are in the “world_nether” with the Mineral Perspective cheat enabled.

**Comment by stonar96** [comment]
Hi, thanks for the tip, I might change that. You can of course adjust the "recommended settings" settings to your own requirements. For example:

```yml
  # Adjust world name.
  world_nether:
    anti-xray:
      # Inherited settings from the default section or overwrite them here.
      ray-trace-blocks:
      # You can add further blocks here,
      # but the max-ray-trace-block-count-per-chunk setting may need to be adjusted.
      - ancient_debris
```
