### ISSUE TITLE
Ores don't seem to be hidden around y level 0.

### ISSUE THREAD

**Issue by MeanKid619** [stonar96/RayTraceAntiXray#4]
![image](https://user-images.githubusercontent.com/64171601/222761417-3cc5b70a-3624-4b4c-9ea4-267cc6812f8a.png)
https://youtu.be/NXqN4OR9MZk
https://youtu.be/xb4-sU7mwXI
I'm unsure if it is something I am doing wrong.
I would really appreciate any help.
I am on paper 1.19.3 latest as of making this issue.

In my paper-world-defaults.yml 
I have:

```yml
anticheat:
  anti-xray:
    enabled: true
    engine-mode: 1
    hidden-blocks:
    - chest
    - diamond_ore
    - deepslate_diamond_ore
    - emerald_ore
    - deepslate_emerald_ore
    - gold_ore
    - deepslate_gold_ore
    - deepslate_iron_ore
    - lapis_ore
    - deepslate_lapis_ore
    - redstone_ore
    - deepslate_redstone_ore
    - spawner
    lava-obscures: false
    max-block-height: 448
    replacement-blocks: []
    update-radius: 2
    use-permission: false
```

In my config.yml of RayTraceAntiXray within plugins folder.
I have:

```yml
settings:
  anti-xray:
    update-ticks: 1
    ms-per-ray-trace-tick: 50
    # Adjust to available (ideally unused) CPU threads.
    ray-trace-threads: 2
world-settings:
  default:
    anti-xray:
      ray-trace: true
      # Be aware that this is about three times as resource intensive.
      ray-trace-third-person: false
      ray-trace-distance: 120
      max-ray-trace-block-count-per-chunk: 120
      rehide-blocks: true
# Blocks that are hidden and ray traced. The hidden-blocks specified in the Paper config file are only hidden if they aren't exposed to transparent blocks. If this list is empty, the hidden-blocks specified in the Paper config file are used.
      ray-trace-blocks: []
      # You can add further blocks here,
      # but the max-ray-trace-block-count-per-chunk setting may need to be adjusted.
  # Adjust world name.
  mechacraft_nether:
    anti-xray:
      # Note that ancient_debris never generates naturally exposed to air.
      # Normal engine-mode: 1 is sufficient, disable ray tracing in the nether.
      ray-trace: false
  # Adjust world name.
  mechacraft_the_end:
    anti-xray:
      ray-trace: false
```
